CREATE TABLE users(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO users (email, password_hash) VALUES (
    'admin@tattoo.com',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
);
